name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn
          yarn build
          yarn test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "releases"
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch
          git merge origin/master --allow-unrelated-histories
      - run: |
          yarn install
          yarn build
          yarn run pack

      - name: Commit changes
        uses: EndBug/add-and-commit@v3
        with:
          author_name: "GitHub Action"
          author_email: action@github.com
          cwd: "."
          message: "Release ${{ github.sha }}"
          path: "."
          pattern: "*.js"
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git push -u
