name: Slack Notify

on: [pull_request, pull_request_review, pull_request_review_comment]

jobs:
  slack-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: davidwallacejackson/pr-notify-action@releases
        with:
          users: "${{secrets.PR_USERS}}"
          slackToken: "${{secrets.SLACK_TOKEN}}"
